rails_olympics_solution/blog_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#new"
  resources :blogs, only: [:show, :new, :index, :create, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :comments, only: [:create, :destroy]
end

rails_olympics_solution/blog_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails_olympics_solution/blog_app/app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  body       :text             not null
#  author_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Blog < ApplicationRecord
  validates :body, :title, presence: true
  validates :title, uniqueness: { scope: :author_id }

  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
end

rails_olympics_solution/blog_app/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :string           not null
#  author_id  :bigint           not null
#  blog_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :author, class_name: 'User'
  belongs_to :blog
end

rails_olympics_solution/blog_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  email      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  has_many :blogs,
    foreign_key: :author_id,
    dependent: :destroy,
    inverse_of: :author

  has_many :comments,
    foreign_key: :author_id,
    dependent: :destroy,
    inverse_of: :author

  #  Find all the comments this user has on their blogs
  has_many :comments_on_blogs,
    through: :blogs,
    source: :comments

  #  Find all the blogs this user has commented on
  has_many :blogs_commented_on,
    through: :comments,
    source: :blog
end

rails_olympics_solution/blog_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_olympics_solution/blog_app/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blogs_url
    else
      render :new
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_url
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body, :author_id)
  end
end

rails_olympics_solution/blog_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to blog_url(@comment.blog_id)
  end

  def destroy
    comment = Comment.find_by(id: params[:id])
    blog_id = comment.blog_id
    comment.destroy
    redirect_to blog_url(blog_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :blog_id, :author_id)
  end
end

rails_olympics_solution/blog_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to blogs_url
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

rails_olympics_solution/blog_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_olympics_solution/blog_app/app/views/blogs/index.html.erb
<h1>All the Blogs!</h1>
<ul>
  <% @blogs.each do |blog| %>
    <li> 
      <a href="<%= blog_url(blog) %>"><%= blog.title %></a> 
    </li>
  <% end %>
  <form action="<%= new_blog_url %>" method="GET">
    <button>New Blog</button>
  </form>
</ul>

rails_olympics_solution/blog_app/app/views/blogs/new.html.erb
<h1>Create a new Blog!</h1>

<form action="<%= blogs_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <label>Choose a blog title:
    <input name ="blog[title]" value="">
  </label>
  <label>What do you have to say?
    <input name ="blog[body]" value="">
  </label>
    <input type="hidden" name ="blog[author_id]" value=<%= User.last.id %>>
  <button type="submit">Create A New Blog</button>
</form>

rails_olympics_solution/blog_app/app/views/blogs/show.html.erb
<h1>Let's look at a Blog!</h1>
<article>

  <h2><%= @blog.title %></h2>

  <%= @blog.body %>

  <form action="<%= blog_url(@blog) %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <button type="submit">Delete Blog</button>
  </form>
</article>


<h5>Comments:</h5>
<ul>
  <%@blog.comments.each do |comment| %>
      <li>
        <%= comment.body %>
        <form action="<%= comment_url(comment) %>" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="DELETE">
          <button type="submit">Delete Comment</button>
        </form>
      </li>
    <% end %>
</ul>

<form action="<%= comments_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Write a Comment:
        <input name ="comment[body]" value="">
    </label>
        <input type="hidden" name ="comment[author_id]" value=<%= User.last.id %>>
        <input type="hidden" name ="comment[blog_id]" value=<%= @blog.id %>>
    <button type="submit">Create A Comment</button>
</form>

rails_olympics_solution/blog_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App (Rails Olympics!)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_olympics_solution/blog_app/app/views/users/new.html.erb
<h1>Create a new User!</h1>

<form action="<%= users_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
      
    <label>Enter your email:
        <input name ="user[email]" value="">
    </label>
    <button type="submit">Create New User</button>
</form>

rails_olympics_solution/blog_app/app/views/users/show.html.erb
<h1>Hello <%= @user.email %>!</h1>